finchcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('finches/<int:finch_id>/', views.detail, name='detail'),
    path('finches/create/', views.finchCreate.as_view(), name='finch_create'),
    path('finches/<int:pk>/update/', views.finchUpdate.as_view(), name='finch_update'),
    path('finches/<int:pk>/delete/', views.finchDelete.as_view(), name='finch_delete'),
    path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
     # associate a toy with a finch (M:M)
    path('finchs/<int:finch_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('finchs/<int:finch_id>/unassoc_toy/<int:toy_id>/', views.unassoc_toy, name='unassoc_toy'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# A tuple of 2-tuples
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Toy(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('toys_detail', kwargs={'pk': self.id})

# Create your models here.
class Finch(models.Model):
  name = models.CharField(max_length=100)
  family = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  toys = models.ManyToManyField(Toy)
  

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('detail', kwargs={'finch_id': self.id})

class Feeding(models.Model):
  date = models.DateField()
  meal = models.CharField(max_length=1,
  # add the 'choices' field option
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0]
  )

  # Create a finch_id FK
  Finch = models.ForeignKey(Finch, on_delete=models.CASCADE)


  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_meal_display()} on {self.date}"

 

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
# Add the following import
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import *
from .forms import FeedingForm


# Define the home routes
def index(request):
    # Grab all finches/
    finches = Finch.objects.all()
    return render(request,'index.html', {'finches': finches})
# Define the about routes
def about(request):
    return render(request,'about.html')
# Define the details routes
def detail(request, finch_id):
    # Grab one finch
    finch = Finch.objects.get(id=finch_id)
    # Get the toys the finch doesn't have
    toys_finch_doesnt_have = Toy.objects.exclude(id__in=finch.toys.all().values_list('id'))
    # instantiate FeedingForm to be rendered in the template
    feeding_form = FeedingForm()
    return render(request, 'finches/detail.html', { 'finch': finch, 'feeding_form': feeding_form , 'toys': toys_finch_doesnt_have})

def add_feeding(request, finch_id):
  # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the finch_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.finch_id = finch_id
    new_feeding.save()
  return redirect('detail', finch_id=finch_id)
#Define create routes
class finchCreate(CreateView):
    model = Finch
    fields = ['name', 'family', 'description']
    success_url = ''
class finchUpdate(UpdateView):
  model = Finch
  fields = ['family', 'description']
    
class finchDelete(DeleteView):
  model = Finch
  success_url = '/'   

class ToyList(ListView):
  model = Toy

class ToyDetail(DetailView):
  model = Toy

class ToyCreate(CreateView):
  model = Toy
  fields = '__all__'

class ToyUpdate(UpdateView):
  model = Toy
  fields = ['name', 'color']

class ToyDelete(DeleteView):
  model = Toy
  success_url = '/toys/' 

def assoc_toy(request, finch_id, toy_id):
  Finch.objects.get(id=finch_id).toys.add(toy_id)
  return redirect('detail', finch_id=finch_id)

def unassoc_toy(request, finch_id, toy_id):
  Finch.objects.get(id=finch_id).toys.remove(toy_id)
  return redirect('detail', finch_id=finch_id)

main_app/templates/about.html
{% extends 'base.html'%} {%block body%} {%endblock%}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>finch Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;finchCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="/about">About</a></li>
            <li><a href="{% url 'finch_create' %}">Add a finch</a></li>
            <li><a href="/admin">Admin Login</a></li>
          </ul>
        </div>
      </nav>
    </header>
    {% block body %} {%endblock %}
    <footer>All Rights Reserved, &copy; 2022 finch Collector</footer>
  </body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html'%} {%block body%}
<!-- add this single line below -->
<h1>finch Details</h1>
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ finch.name }}</span>
    <p>Family: {{ finch.family }}</p>
    <p>Description: {{ finch.description }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'finch_update' finch.id %}">Edit</a>
    <a href="{% url 'finch_delete' finch.id %}">Delete</a>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' finch.id %}" method="post">
      {% csrf_token %} {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- This is all new markup to be added just above the <script> tag -->
<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Toys</h3>
    {% if finch.toys.count %} {% for toy in finch.toys.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color: {{ toy.color }}">{{ toy.color }}</span>
          {{ toy.name }}
        </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Toys :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if finch.toys.count %} {% for toy in toys.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{
          toy.name }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_toy' finch.id toy.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{finch.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>
<script>
  const dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });
  // add additional JS to initialize select below
  const selectEl = document.getElementById("id_meal");
  M.FormSelect.init(selectEl);
</script>
{%endblock%}

main_app/templates/index.html
{% extends 'base.html'%} {%block body%}
<h1>finch List</h1>

{% for finch in finches %}
<div class="card">
  <div class="card-content">
    <span class="card-title"
      ><a href="/finches/{{ finch.id }}">{{ finch.name }}</a></span
    >
    <p>family: {{ finch.family }}</p>
    <p>Description: {{ finch.description }}</p>
  </div>
</div>
{% endfor %} {%endblock%}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %} {% block body %}
<h1>Delete finch</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
</form>
<br />
<a href="{% url 'detail' finch.id %}">Cancel</a>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html'%} {%block body%} {% if object %}
<h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
<h1>Add finch</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    <!-- form is an instance of a ModelForm class -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{%endblock%}